
project: spring-ai-demo
confirm: Are you sure you want to run on {{stage}}?


# Set this if you want to carry over parent process' environment variables
# carry_env: true 


#
# Variables
#
# Feel free to add options here to be used as a variable throughout
# paths.
#
opts:
  stage: env:ENVIRONMENT_CONFIG_FILE


#
# Providers
#
providers:
  # you can mix and match many files
  dotenv:
    env_sync:
      path: ./{{stage}}
    env:
      TEST_ENVIRONMENT_VARIABLE:
        path: ./{{stage}}
      DEEPSEEK_API_KEY:
        path: ./{{stage}}
      DEEPSEEK_URL:
        path: ./{{stage}}


